### ISSUE TITLE
Failed to activate the precss package

### ISSUE THREAD

**Issue by zslabs** [zhouwenbin/atom-precss#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [precss](https://github.com/zhouwenbin/atom-precss) package, v0.3.0
### Stack Trace

Failed to activate the precss package

```
At processor.plugin is not a function

TypeError: processor.plugin is not a function
    at /Users/zachschnackel/.atom/packages/precss/node_modules/precss/index.js:104:27
    at Array.forEach (native)
    at /Users/zachschnackel/.atom/packages/precss/node_modules/precss/index.js:91:13
    at creator (/Users/zachschnackel/.atom/packages/precss/node_modules/postcss/lib/postcss.js:60:39)
    at Function.postcss.plugin (/Users/zachschnackel/.atom/packages/precss/node_modules/postcss/lib/postcss.js:66:23)
    at Object.<anonymous> (/Users/zachschnackel/.atom/packages/precss/node_modules/precss/index.js:85:26)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zachschnackel/.atom/packages/precss/index.js:2:30)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:166:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:740:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:05.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 precss (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
atom-handlebars, v1.3.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
language-babel, v2.6.3
language-blade, v0.16.0
laravel, v0.7.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-eslint, v5.2.7
linter-handlebars, v2.3.1
linter-jshint, v1.2.2
linter-less, v2.3.3
linter-scss-lint, v2.5.0
pigments, v0.19.5
precss, v0.3.0
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by zhouwenbin** [comment]
@zslabs try install node and update your atom verson

**Comment by zslabs** [comment]
Current node version is `4.0.0` and Atom is the latest version. Is there a minimum version required?

**Comment by zhouwenbin** [comment]
@zslabs my atom verson is 1.2.4,let me try 1.3.2

**Comment by zhouwenbin** [comment]
@zslabs I have update atom and has not any problem.my apm verson is

```
apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
```

try to delect the precss package and install with apm

```
apm install precss
```

**Comment by zslabs** [comment]
Thanks. `apm install` did it.
